# Generated by Django 5.2 on 2025-04-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Cliente')),
                ('telefono', models.CharField(max_length=10, unique=True, verbose_name='Telefono del Cliente')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo del Cliente')),
                ('contrasenia', models.CharField(max_length=32, verbose_name='Contraseña')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
            ],
        ),
    ]
